enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns= [
    path('', views.IndexView.as_view(), name='index'),
    # path('enquente/<int:pk>', views.DetalhesView.as_view(), name='detalhes'),
    path('enquente/<int:pk>/resultado', views.ResultadoView.as_view(), name='resultado'),
    path('enquente/<int:id_enquete>/votacao', views.votacao, name='votacao'),
    path('enquente/<int:id_enquete>', views.detalhes, name='detalhes'),
    path('enquente/categoria/<int:id_category>', views.categories, name='categorias'),
    #path('enquente/<int:id_enquete>/resultado', views.ResultadoView.as_view(), name='resultado'),
    #path('enquente/<int:id_enquete>/votacao', views.votacao, name='votacao'),
] 

main/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    started_at = models.DateTimeField('Data de criação')

    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title

class Question(models.Model):
    text = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('Data de Publicação')
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['text']

    def publicada_recentemente(self):
        agora = timezone.now()
        return agora - datetime.timedelta(days=1) <= self.data_publicacao <= agora

    publicada_recentemente.admin_order_field = 'data_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'RECENTEMENTE PUBLICADA? (<24H)'

class Polls(models.Model):
    title = models.CharField(max_length=200)
    create_at = models.DateTimeField('Data de criação')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
class Choice(models.Model):
    text = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Question, Choice, Category
from django.views import generic
from django.urls import reverse
from django.utils import timezone

# Create your views here.
#def index(request):
    #ultimas_perguntas = Question.objects.order_by('-data_publicacao')[:5]
    #contexto = {'ultimas_perguntas': ultimas_perguntas}
    #return render(request, 'main/index.html', contexto)

def detalhes(request, id_enquete):
    pergunta = get_object_or_404(Question, pk=id_enquete)
    category = Category.objects.get(question__id=pergunta.id)
    return render(request, 'main/detalhes.html', {'question': pergunta, 'category': category})

#def resultado(request, id_enquete):
    #pergunta = get_object_or_404(Question, pk=id_enquete)
    #return render(request, 'main/resultado.html', {'pergunta': pergunta})

class IndexView(generic.ListView):
    template_name = "main/index.html" #optional
    context_object_name = 'ultimas_perguntas' #optional
    def get_queryset(self):
        return Question.objects.filter(data_publicacao__lte = timezone.now()).order_by('-data_publicacao')[:5]

# class DetalhesView(generic.DetailView):
#     model = Question #optional
#     template_name = "main/detalhes.html" #optional

#     def get_queryset(self):
#         return Question.objects.filter(data_publicacao__lte = timezone.now())

class ResultadoView(generic.DetailView):
    template_name = "main/resultado.html" #optional
    model = Question #optional

def votacao(request, id_enquete):
    pergunta = get_object_or_404(Question, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.choice_set.get(pk=request.POST['opcao'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'main/detalhes.html',  {
            'pergunta': pergunta,
            'error_message': "Selecione uma opção Válida!"
        })
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
    return HttpResponseRedirect(reverse('main:resultado', args=(pergunta.id,)))

def categories(request, id_category):
    category = get_object_or_404(Category, pk=id_category)
    return render(request, 'main/categorias.html', {'category': category})

main/templates/main/categorias.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>App Enquete</title>
</head>

<body>
  <h1><strong>Categoria: {{ category.title }} </strong></h1>
  <h2>Descrição da categoria: </h2>
  <p>{{ category.description }}</p>
  <h2>Criada em: {{ category.started_at }}</h2>
  <hr>
  <h3>Perguntas relacionadas:</h3>
  {% if error_message %}
  <hr>
  <strong>{{ error_message }} </strong>
  <hr>
  {% endif %}
  <ul>
    {% for question in category.question_set.all %}
    <li>
      <a href="{% url 'main:detalhes' question.id %}">
        <h4>Pergunta: {{ question.text }}</h4>
      </a>
    </li>
    {% endfor %}
  </ul>
  <a href="{% url 'main:index' %}" class="btn btn-danger">Home</a>
</body>

</html>

main/templates/main/detalhes.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>App Enquete</title>
</head>

<body>
  <h1><strong>Categoria: <a href="{% url 'main:categorias' category.id %}"> {{ category.title }} </a> </strong></h1>
  <h2>Descrição da categoria: </h2>
  <p>{{ category.description }}</p>
  <h2>Criada em: {{ category.started_at }}</h2>
  <hr>
  <h3>Detalhes da Enquete {{ question.id }}</h3>
  <u>Pergunta:</u> {{ question.text }} <br>
  <u>Data de publicação:</u> {{ question.data_publicacao }} <br>
  {% if error_message %}
  <hr>
  <strong>{{ error_message }} </strong>
  <hr>
  {% endif %}
  <form action="{% url 'main:votacao' question.id %}" method='post'>
    {% csrf_token %}
    <ul>
      {% for opcao in question.choice_set.all %}
      <li>
        <input type='radio' name='opcao' id="opcao{{forloop.counter}}" value={{opcao.id}} />
        <label for="opcao{{forloop.counter}}">
          {{ opcao.text }}
        </label>
      </li>
      {% endfor %}
    </ul>
    <input type="submit" value="Registre o seu voto" />
  </form>
</body>

</html>

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>App Enquete</title>
  <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">
</head>

<body>
  {%if ultimas_perguntas %}
  <h2>Lista das Útimas Enquetes</h2>
  <ul>
    {% for pergunta in ultimas_perguntas %}
    <li>
      <a href="{% url 'main:detalhes' pergunta.id %}">
        {{ pergunta.text }}
      </a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <h3>Não há enquetes cadastradas até o momento!</h3>
  {% endif %}

</body>

</html>

main/templates/main/resultado.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>App Enquete</title>
</head>

<body>
  <h2>Resultado parcial da Enqeunte {{ question.id }}</h2>
  <u>Pergunta:</u> {{ question.text }} <br>
  <u>Data de publicação:</u> {{ question.data_publicacao }}

  <ul>
    {% for opcao in question.opcao_set.all %}
      <li> {{ opcao.text }} = {{ opcao.votos }} voto{{ opcao.votos | pluralize}}</li>
    {% endfor %}
  </ul>

  <hr>

  <a href=" {%url 'main:detalhes' question.id %}">Deseja votar novamente</a>
  <br>
  <a href=" {%url 'main:index'%}">Retornar para a página principal </a>

</body>

</html>